roster_caption = {
"omnycacupunctureny": "www.omnycacupuncture.com (212)564-5953 #eczema #dermatology #omnycacupunctureny #nycacupuncture #acupuncture #atopic #acupuncturist #cosmeticacupuncture #iloveacupuncture #skincare #acutherapy #chinesemedicine #herbal #natural #psoriasis #beauty #diet #relaxation #nycktown #naturalhealth",
"theartnailandspa" : "(609)799-7887 #present #theartandnailsspa #nail #nails #nailsalon #spa #beauty #springnails #gelmanicure #massage #manicure #pedicure #nailpolish #plainsboro #frenchmanicure #weeklypolish",
"oasisnailandspanj" : "(973) 334-0303 http://oasisnailandspanj.com/ #oasisnailandspa #boontonnail #footmassage #reflexology #bestnailsalon #pedicure #manicure #relaxation",
"jsgolfnj" : "(201) 787-5737 #ijgttournament #golftournament #jsgolf #newjersey #golfschool #golflesson #golfacademy #golf #sports #golfer #golfing #golfcoach #golfshot #chipping #pga #golftips",
"maison_de_mi_salon" : "(917) 549-0242 (212) 725-1460 #maisondemi #nychairsalon #hairstylist #haircolor #hair #hairsalon #manhattan #뉴욕 #맨하탄 #한인타운 #메종드미 #salon #cut #style #perm #color #nyc #염색",
"organiquenailspanj" : "(201) 767-8300 #organiquenailspa #nails #nailsofinstagram #nails💅 #nailart #pedicure #pedi #spa #manicure #fingers #bestnailsalon #spapedicure",
"starsunnyspanjnj" : "(201) 482-4153 #starsunnyspa #palisadespark #massage #reflexology #footmassage #backmassage #healing #relaxation #spa #couplemassage",
"danwooenterprise" : "#cars #rides #ride #speed #buy #deals #Honda #Kia #lease #Nissan #nice #car #needforspeed #underground #racing",
"fourseasonstherapy" : "(425) 512-5890 #fourseasonstherapy #everett #WA #massage #reflexology #footmassage #backmassage #healing #relaxation #health #healthclub #spa #beauty #beautygram #pamper #relax",
"edennail_manalapan" : "(732) 851-7711 #edennail #manalapan #edennail_manalapan #nail #nails #nailsalon #spa #beauty #springnails #gelmanicure #massage #manicure #pedicure #nailpolish #frenchmanicure #weeklypolish",
"edennailnspa_westfield" : "(908) 317-9300 #edennail #westfield #edennailnspa_westfield #nail #nails #nailsalon #beauty #gelmanicure #manicure #pedicure #nailpolish #weeklypolish",
"edennail_newprovidence" : "(908) 516-2162 #edennail #newprovidence #edennail_newprovidence #nail #nails #nailsalon #spa #beauty #springnails #gelmanicure #massage #manicure #pedicure #nailpolish #frenchmanicure #weeklypolish",
"edennail_parkridge" : "(201) 476-0220 #edennail #parkridge #edennail_parkridge #nail #nails #nailsalon #spa #beauty #springnails #gelmanicure #massage #manicure #pedicure #nailpolish #frenchmanicure #weeklypolish",
"1nailsalonoradell" : "(201) 986-1322 #1nailsalonoradell #oradell #nails #nailsofinstagram #nails💅 #nailart #pedicure #manicure #bestnailsalon #spapedicure #relaxation",
"largohousespa_nail" : "www.spalargohouse.com/ (973) 777-9784 #largohousespa #nails #nailsalon #spa #beauty #gelmanicure #massage #manicure #nailart",
"twoelitenails" :"(201)348-1100 #twoelitenails #northbergen #nj #nail #nails #bestnails #nailsalon #spa #beauty #fallnails #nailart #gelmanicure #massage #manicure #pedicure #nailpolish #frenchmanicure #weeklypolish",
"newtokyonailsalon" : "(845)298-1888 #newtokyonailsalon #best #happy #fleek #nail #nails #bestnails #nailsalon #spa #beauty #fallnails #nailart #gelmanicure #massage #manicure #pedicure #nailpolish #frenchmanicure #weeklypolish",
"98bodyworkspa" :"(347)506-5182 #98bodyworkspa #eastelmhurst #ny #chill #soothing #massagetherapy #asiangirls #asiangirlsmassage #massagegirls #nomorestress #tableshower #deeptissuemassage #swedishmassage #hotstonemassage",
"beautistarinc@gmail.com" : "(201)944-1007 #beautistarnj #lashextensions #lashes #lash #lashextension #permanentmakeup #individuallashes #eyelashextensions",
"pureharmonyspa_ct" : "(203)693-3334 #pureharmonyspa_ct #milford #ct #chill #soothing #massagetherapy #asiangirls #asiangirlsmassage #massagegirls #nomorestress",
"thanksnailnj" : "(201) 372-0078 #thanksnailnj #nails #nailsalon #beauty #gelmanicure #massage #manicure #pedicure #nailpolish #frenchmanicure",
"thecurtain_newjersey" : "(201) 302-9111 #thecurtain #curtains #prettyhome #home #decor #homedecor #myhome #dreamhouse #dream #house #shades #beautiful #colors #fancy",
"stellanailscaldwell" : "(973) 226-7755 #stellanailscaldwell #nail #nails #nailsalon #spa #beauty #gelmanicure #massage #manicure #pedicure #nailpolish #frenchmanicure #weeklypolish",
"stellanailsnj" : "(973) 226-7755 #stellanailscaldwell #nail #nails #nailsalon #spa #beauty #gelmanicure #massage #manicure #pedicure #nailpolish #frenchmanicure #weeklypolish",
"dolcenailsct" : "(203) 656-4499 #dolcenailsct #nail #nails #nailsalon #spa #beauty #gelmanicure #manicure #pedicure #nailpolish #frenchmanicure #weeklypolish #treat #nailart",
"vestalnails" : "(607) 239-6002 #vestalnails #nail #nails #nailsalon #spa #beauty #gelmanicure #manicure #pedicure #nailpolish #frenchmanicure #weeklypolish #treat #nailart",
"greennailsnj" : "(973) 701-6700 #nj #nail #nails #nailsalon #spa #beauty #gelmanicure #manicure #pedicure #nailpolish #frenchmanicure #weeklypolish #treat #nailart #best #happy #fleek",
"unicornnailssyracuse" : "(315)251-0100 #nail #nails #nailsalon #spa #beauty #gelmanicure #manicure #pedicure #nailpolish #frenchmanicure #weeklypolish #treat #nailart #best #happy #fleek",
"oceansushilp" : "(315) 622-6050 #liverpoolny #ny #sushi #rolls #handroll #special #seafood #japanese #food #udon #tekadon #chirashi #donburi #soup #rice #lunch #dinner #foodstagram #salmon #tuna",
"familynailoradellnj" : "#nail #nails #nailsalon #spa #beauty #gelmanicure #manicure #pedicure #nailpolish #frenchmanicure #weeklypolish #treat #nailart #best #happy #fleek",
"scarsdalepeony" : "#nail #nails #nailsalon #spa #beauty #gelmanicure #manicure #pedicure #nailpolish #frenchmanicure #weeklypolish #treat #nailart #best #happy #fleek #lash #lashes #lashwork",
"doshirak_box" : "(718) 358-2798 #doshirak #flushing #ny #korean #koreatown #food #yum #kimbap #bibimbap #ramen #koreanfood #delicious #lunch #dinner #instagood",
"dqr_pets" : "#breeder #cute #frenchbulldog #cutedogs #pomeranian #instapets #petstagram #puppystagram #pupstagram #pup #puppy #poodle #maltipoo #pomsky #doglover #puppylife #강아지 #개스타그램 #댕댕이 #NJpets #NYPets",
"lulu_lavender_nyc" : "#nail #nails #nailsalon #spa #beauty #gelmanicure #manicure #pedicure #nailpolish #frenchmanicure #weeklypolish #treat #nailart",
}